[tools]
# global tool versions go here
# you can set these with `mise use -g`
python = ["latest", "3.12", "3.10"]
erlang = "latest"
elixir = "latest"
ruby = "latest"
elm = "latest"
nim = "latest"
node = "lts"
pnpm = "latest"
# bun = "latest"
deno = "latest"
usage = "latest"
java = "temurin-21"
"npm:elm-oracle" = "latest"
"npm:elm-review" = "latest"
"npm:elm-live" = "latest"
"npm:cliui" = "latest"
"npm:vscode-markdown-languageserver" = "latest"
"npm:eslint" = "latest"
"npm:npm-name-cli" = "latest"
"npm:np" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:npm-check" = "latest"
"npm:yaml-language-server" = "latest"
"npm:npm-check-updates" = "latest"
"npm:stylus" = "latest"
"npm:less" = "latest"
"npm:basedpyright" = "latest"
"npm:js-beautify" = "latest"
"npm:emmet-ls" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:git-recent" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:neovim" = "latest"
"npm:stylelint" = "latest"
"npm:prettier-plugin-elm" = "latest"
"npm:wscat" = "latest"
"npm:bash-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:import-js" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:diagnostic-languageserver" = "latest"
"npm:elm-test" = "latest"
"npm:@elm-tooling/elm-language-server" = "latest"
"npm:@vue/language-server" = "latest"
"npm:elm-format" = "latest"

[settings]
# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
idiomatic_version_file = false            # enabled by default (unlike asdf)
# idiomatic_version_file_disable_tools = [] # disable for specific tools
idiomatic_version_file_enable_tools = [] # enable for specific tools

# configure `mise install` to always keep the downloaded archive
always_keep_download = false        # deleted after install by default
always_keep_install = false         # deleted on failure by default

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdx/mise/issues/128)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

# config files with these prefixes will be trusted by default
trusted_config_paths = ['~/workspace']

verbose = false       # set to true to see full installation output, see `MISE_VERBOSE`
http_timeout = "30s"  # set the timeout for http requests as duration string, see `MISE_HTTP_TIMEOUT`
jobs = 4              # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false           # set to true to directly pipe plugins to stdin/stdout/stderr
yes = false           # set to true to automatically answer yes to all prompts

not_found_auto_install = true # see MISE_NOT_FOUND_AUTO_INSTALL
task_output = "prefix" # see Tasks Runner for more information
paranoid = false       # see MISE_PARANOID

shorthands_file = '~/.config/mise/shorthands.toml' # path to the shorthands file, see `MISE_SHORTHANDS_FILE`
disable_default_shorthands = false # disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`
# disable_tools = ['node']           # disable specific tools, generally used to turn off core tools

env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`

experimental = true # enable experimental features
python_compile = false
ruby.compile = true

npm.package_manager = "pnpm"

# configure messages displayed when entering directories with config files
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }

# "_" is a special key for information you'd like to put into mise.toml that mise will never parse
[_]
# foo = "bar"